name: Release VSCode Extension

on:
  push:
    tags:
      - "v*" # Triggers on tags like v0.0.1, v1.2.3, etc.

jobs:
  release:
    name: Publish Extension to Marketplace
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Compile extension
        run: yarn package

      - name: Publish to VSCode Marketplace
        run: npx vsce publish -p ${{ secrets.VSCE_TOKEN }}
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
